export type Activity = {
  id: string;
  name: string;
  nameEn?: string;
  nameJa?: string;
  nameMy?: string;
  duration: number; // in minutes
  isOptional: boolean;
  location?: string;
  style?: string; // e.g., 'Traditional', 'Western'
  details?: string;
  bgm?: string;
  isImportant?: boolean;
  needsMic?: boolean;
  onStage?: boolean;
  responsible?: string; // e.g., 'MC', 'Venue', 'Couple'
  coordinationNotes?: string;
  coordinationNotesJa?: string;
  coordinationNotesMy?: string;
  bgmUrl?: string;
  projector?: string;
  staffNotes?: {
    mc?: string;
    photo?: string;
    lighting?: string;
    escort?: string;
  };
  isPrep?: boolean;
  startOffset?: number;
  subActivities?: Activity[];
};

export type ActivityCategory = {
  name: string;
  activities: Activity[];
};

export const PREDEFINED_ACTIVITY_CATEGORIES: ActivityCategory[] = [
  {
    name: 'Preparation & Arrival',
    activities: [
      { 
        id: 'prep', 
        name: 'Venue Preparation', 
        nameEn: 'Venue Preparation',
        nameJa: '会場準備',
        nameMy: 'နေရာပြင်ဆင်ခြင်း',
        duration: 60, 
        isOptional: false, 
        responsible: 'Staff', 
        isPrep: true 
      },
      { 
        id: '1', 
        name: 'Reception', 
        nameEn: 'Reception',
        nameJa: '受付',
        nameMy: 'ဧည့်ခံ',
        duration: 30, 
        isOptional: false, 
        isImportant: true, 
        responsible: 'Venue' 
      },
      { id: 'p1', name: 'Bride & Groom Arrival', nameJa: '新郎新婦レストラン入り', nameMy: 'သတို့သားသတို့သမီး ရောက်ရှိ', duration: 10, isOptional: false, isPrep: true, responsible: 'Couple' },
      { id: 'p2', name: 'Champagne Brunch', nameJa: 'シャンパンブランチ', nameMy: 'ရှန်ပိန်ဘбранချီ', duration: 30, isOptional: false, isPrep: true, responsible: 'Venue' },
      { id: 'p3', name: 'Bride Prep Start', nameJa: '新婦お支度開始', nameMy: 'သတို့သမီး ပြင်ဆင်မှုစတင်', duration: 90, isOptional: false, isPrep: true, responsible: 'Makeup' },
      { id: 'p4', name: 'Hair & Makeup Finished', nameJa: '新郎新婦ヘアメイク仕上がり', nameMy: 'ဆံပင်နှင့် မိတ်ကပ် ပြီးစီး', duration: 0, isOptional: false, isPrep: true, responsible: 'Makeup' },
      { id: 'p5', name: 'Couple Photo Shoot', nameJa: 'お二人写真撮影（記念orスナップ）', nameMy: 'ဇနီးမောင်နှံ ဓာတ်ပုံရိုက်ကူးခြင်း', duration: 30, isOptional: false, isPrep: true, responsible: 'Photographer' },
      { id: 'p6', name: 'Bride Room Photo', nameJa: 'ブライズで撮影(撮影PLANに応じて）', nameMy: 'သတို့သမီးအခန်းတွင် ဓာတ်ပုံရိုက်ခြင်း', duration: 15, isOptional: false, isPrep: true, responsible: 'Photographer' },
      { id: 'p7', name: 'Relatives Receptionist Arrival', nameJa: '親族受付ご担当者様来館', nameMy: 'ဆွေမျိုးများ ဧည့်ကြို ရောက်ရှိ', duration: 0, isOptional: false, isPrep: true, responsible: 'Guests' },
      { id: 'p8', name: 'Ceremony Rehearsal', nameJa: '挙式リハーサル', nameMy: 'မင်္ဂလာပွဲ အစမ်းလေ့ကျင့်ခြင်း', duration: 20, isOptional: false, isPrep: true, responsible: 'MC/Staff' },
      { id: 'p9', name: 'Gold Plate Affixing', nameJa: 'ゴールドプレート貼りつけ', nameMy: 'ရွှေပြားကပ်ခြင်း', duration: 5, isOptional: false, isPrep: true, responsible: 'Couple' },
      { id: 'p10', name: 'Relatives Reception', nameJa: '親族受付', nameMy: 'ဆွေမျိုးများ ဧည့်ခံ', duration: 30, isOptional: false, isPrep: true, responsible: 'Receptionist' },
      { id: 'p11', name: 'Guest Reception', nameEn: 'Guest Reception', nameJa: 'ゲスト受付', nameMy: 'ဧည့်သည်များ ဧည့်ခံ', duration: 30, isOptional: false, isPrep: true, responsible: 'Receptionist' },
      { id: 'p12', name: 'Relatives Group Photo', nameEn: 'Relatives Group Photo', nameJa: '親族集合写真（記念）', nameMy: 'ဆွေမျိုးများ စုပေါင်းဓာတ်ပုံ', duration: 15, isOptional: false, isPrep: true, responsible: 'Photographer' },
      { id: 'p13', name: 'Waiting for Entrance', nameEn: 'Waiting for Entrance', nameJa: '入場待機', nameMy: 'ဝင်ရောက်ရန် စောင့်ဆိုင်းခြင်း', duration: 10, isOptional: false, isPrep: true, responsible: 'Couple' },
      { id: 'pa1', name: 'Chapel Photoshoot', nameEn: 'Chapel Photoshoot', nameJa: 'チャペル撮影', nameMy: 'ချပယ် ဓာတ်ပုံရိုက်ကူးခြင်း', duration: 20, isOptional: false, isPrep: true, responsible: 'Photographer' },
      { id: 'pa2', name: 'Group Photo — 2F', nameEn: 'Group Photo — 2F', nameJa: '集合写真（2F）', nameMy: 'စုပေါင်းဓာတ်ပုံ（2F）', duration: 15, isOptional: false, isPrep: true, responsible: 'Photographer' },
      { id: 'pa3', name: 'MC Preparation & BGM Confirm', nameEn: 'MC Preparation & BGM Confirm', nameJa: 'MC準備・BGM確認', nameMy: 'MC ပြင်ဆင်မှုနှင့် BGM အတည်ပြုခြင်း', duration: 15, isOptional: false, isPrep: true, responsible: 'MC' },
    ]
  },
  {
    name: 'Main Ceremony',
    activities: [
      { 
        id: '2', 
        name: 'Ceremony Start & Entrance', 
        nameEn: 'Ceremony Start & Entrance',
        nameJa: '開宴・新郎新婦入場',
        nameMy: 'ပွဲစတင်ခြင်းနှင့် သတို့သား၊ သတို့သမီး ဝင်ရောက်ခြင်း',
        duration: 5, 
        isOptional: false, 
        isImportant: true, 
        needsMic: true, 
        onStage: true, 
        responsible: 'MC' 
      },
      { 
        id: '6', 
        name: 'Ring Exchange', 
        nameEn: 'Ring Exchange',
        nameJa: '指輪交換',
        nameMy: 'လက်စွပ်လဲလှယ်ခြင်း',
        duration: 5, 
        isOptional: false, 
        onStage: true, 
        responsible: 'Couple' 
      },
      { 
        id: '7', 
        name: 'Love Speech', 
        nameEn: 'Love Speech',
        nameJa: '誓いの言葉',
        nameMy: 'Love Speech',
        duration: 5, 
        isOptional: false, 
        needsMic: true, 
        onStage: true, 
        responsible: 'Couple' 
      },
      { 
        id: '8', 
        name: 'Announcement of Marriage', 
        nameEn: 'Announcement of Marriage',
        nameJa: '結婚宣言',
        nameMy: 'မင်္ဂလာပွဲအောင်မြင်စွာပြီးမြောက်ကြောင်းကြေညာခြင်း',
        duration: 5, 
        isOptional: false, 
        needsMic: true, 
        onStage: true, 
        responsible: 'MC' 
      },
      { 
        id: '13', 
        name: 'Welcome Speech & Cheers', 
        nameEn: 'Welcome Speech & Cheers',
        nameJa: 'ウェルカムスピーチ・乾杯',
        nameMy: 'ကြိုဆိုနှုတ်ခွန်းဆက်စကားနှင့် Cheers',
        duration: 5, 
        isOptional: false, 
        needsMic: true, 
        onStage: true, 
        responsible: 'MC' 
      },
      { 
        id: '14', 
        name: 'Cake Cutting', 
        nameEn: 'Cake Cutting',
        nameJa: 'ケーキ入刀',
        nameMy: 'ကိတ်မုန့်လှီးဖြတ်ခြင်း',
        duration: 5, 
        isOptional: false, 
        onStage: true, 
        responsible: 'MC' 
      },
      { 
        id: '16', 
        name: 'Thank You Speech & Exit', 
        nameEn: 'Thank You Speech & Exit',
        nameJa: '謝辞・新郎新婦退場',
        nameMy: 'ကျေးဇူးတင်စကားနှင့် သတို့သား၊ သတို့သမီးထွက်ခွာခြင်း',
        duration: 5, 
        isOptional: false, 
        needsMic: true, 
        onStage: true, 
        responsible: 'Couple' 
      },
      { 
        id: 'exit', 
        name: 'Party End', 
        nameEn: 'Party End',
        nameJa: '新郎新婦退場',
        nameMy: 'Party End 新郎新婦退場',
        duration: 5, 
        isOptional: false, 
        isImportant: true, 
        onStage: true, 
        needsMic: true, 
        responsible: 'Couple' 
      },
      { id: 'c1', name: 'Civil Ceremony', nameJa: '人前式', nameMy: 'လူရှေ့သက်သေပြု မင်္ဂလာပွဲ', duration: 20, isOptional: false, isImportant: true, onStage: true, responsible: 'MC' },
      { id: 'c2', name: 'Flower/Ring Procession', nameJa: 'フラワー撒く人・指輪持つ人', nameMy: 'ပန်းကြဲသူ / လက်စွပ်သယ်သူ', duration: 5, isOptional: false, onStage: true, responsible: 'Guests' },
      { id: 'c3', name: 'Vows', nameJa: '誓いの言葉', nameMy: 'သစ္စာဆိုခြင်း', duration: 5, isOptional: false, needsMic: true, onStage: true, responsible: 'Couple' },
      { id: 'c4', name: 'Ring Reveal', nameJa: 'リングお披露目', nameMy: 'လက်စွပ်ပြသခြင်း', duration: 3, isOptional: false, onStage: true, responsible: 'Couple' },
      { id: 'c5', name: 'Sign Certificate', nameJa: '結婚証明書サイン', nameMy: 'လက်မှတ်ရေးထိုးခြင်း', duration: 5, isOptional: false, onStage: true, responsible: 'Couple' },
      { id: 'c6', name: 'Show Certificate', nameJa: '結婚証明書披露', nameMy: 'လက်မှတ်ပြသခြင်း', duration: 3, isOptional: false, onStage: true, responsible: 'Couple' },
      { id: 'c7', name: 'Applause', nameJa: '承認の拍手', nameMy: 'လက်ခုပ်တီး အသိအမှတ်ပြုခြင်း', duration: 2, isOptional: false, onStage: true, responsible: 'Guests' },
      { id: 'c8', name: 'Closing Words', nameJa: '閉会の言葉', nameMy: 'နိဂုံးချုပ်စကား', duration: 3, isOptional: false, needsMic: true, onStage: true, responsible: 'MC' },
      { id: 'c9', name: 'Ceremony Exit', nameJa: '新郎新婦退場', nameMy: 'သတို့သားသတို့သမီး ထွက်ခွာခြင်း', duration: 5, isOptional: false, isImportant: true, onStage: true, responsible: 'Couple' },
    ]
  },
  {
    name: 'Ceremony Entrance Flow',
    activities: [
      {
        id: 'ce1',
        name: 'Opening Slideshow',
        nameEn: 'Opening Slideshow',
        nameJa: 'スライドショー上映',
        nameMy: 'Slideshow ပြသခြင်း',
        duration: 5,
        isOptional: false,
        responsible: 'Tech',
        coordinationNotes: 'Plays before the couple entrance begins'
      },
      {
        id: 'ce2',
        name: 'Groom Entrance (with Friends)',
        nameEn: 'Groom Entrance (with Friends)',
        nameJa: '新郎入場（友人と共に）',
        nameMy: 'သတို့သား ဝင်ရောက်ခြင်း（သူငယ်ချင်းများနှင့်）',
        duration: 5,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Groom',
        coordinationNotes: 'Groom enters with friends, waits at centre of the floor'
      },
      {
        id: 'ce3',
        name: 'Bride Entrance (with Father)',
        nameEn: 'Bride Entrance (with Father)',
        nameJa: '新婦入場（父と共に）',
        nameMy: 'သတို့သမီး ဝင်ရောက်ခြင်း（ဖခင်နှင့်）',
        duration: 5,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Bride',
        coordinationNotes: 'Bride walks in escorted by her father'
      },
      {
        id: 'ce4',
        name: 'Father Handover',
        nameEn: 'Father Handover',
        nameJa: 'お父様よりバトンタッチ（引き渡し）',
        nameMy: 'ဖခင်မှ သတို့သားထံ လက်ပြောင်းခြင်း',
        duration: 3,
        isOptional: false,
        onStage: true,
        responsible: 'Couple',
        coordinationNotes: 'Father hands bride over to groom'
      },
      {
        id: 'ce5',
        name: 'Virgin Road Walk (Together)',
        nameEn: 'Virgin Road Walk (Together)',
        nameJa: 'お二人でバージンロード',
        nameMy: 'Virgin Road လမ်းလျှောက်ခြင်း（နှစ်ဦးအတူ）',
        duration: 5,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Couple',
        bgm: 'Virgin Road BGM'
      },
      {
        id: 'ce6',
        name: 'Ceremony',
        nameEn: 'Ceremony',
        nameJa: '挙式',
        nameMy: 'မင်္ဂလာပွဲ ကျင်းပခြင်း',
        duration: 15,
        isOptional: false,
        isImportant: true,
        onStage: true,
        needsMic: true,
        responsible: 'MC'
      },
      {
        id: 'ce7',
        name: 'First Kiss',
        nameEn: 'First Kiss',
        nameJa: 'ファーストキス',
        nameMy: 'ပထမဆုံး နမ်းရှုပ်ခြင်း',
        duration: 3,
        isOptional: true,
        onStage: true,
        responsible: 'Couple'
      },
    ]
  },
  {
    name: 'Burmese Traditional Ceremony',
    activities: [
      { 
        id: '3', 
        name: 'Su Lya Yit Pat', 
        nameEn: 'Su Lya Yit Pat',
        nameJa: 'スーリャ・イッ・パッ (ミャンマー伝統儀式)',
        nameMy: 'စုလျားရစ်ပတ်',
        duration: 15, 
        isOptional: true, 
        onStage: true, 
        responsible: 'Couple' 
      },
      { 
        id: '4', 
        name: 'Traditional Greeting', 
        nameEn: 'Traditional Greeting',
        nameJa: 'ミャンマー伝統の挨拶',
        nameMy: 'မြန်မာ့ရိုးရာနှုတ်ဆက်ဂါရဝပြုခြင်း',
        duration: 10, 
        isOptional: false, 
        onStage: true, 
        responsible: 'Couple' 
      },
      { 
        id: '5', 
        name: 'Water Pouring & Garland', 
        nameEn: 'Water Pouring & Garland',
        nameJa: '水合わせ・花輪の儀式',
        nameMy: 'ရေစင်သွန်း ၊ ပန်းကုံးစွပ် စသည့်စုလျားရစ်ပတ်မင်္ဂလာ',
        duration: 5, 
        isOptional: false, 
        onStage: true, 
        responsible: 'Couple' 
      },
    ]
  },
  {
    name: 'Reception & Entertainment',
    activities: [
      { 
        id: '9', 
        name: 'Meal & Conversation', 
        nameEn: 'Meal & Conversation',
        nameJa: '食事・歓談',
        nameMy: 'အစားအသောက်နှင့် နှုတ်ဆက်စကားပြောဆိုခြင်း',
        duration: 45, 
        isOptional: false, 
        responsible: 'Venue' 
      },
      { 
        id: '12', 
        name: 'Video & Performance', 
        nameEn: 'Video & Performance',
        nameJa: '映像上映・余興',
        nameMy: 'ဗီဒီယိုပြသခြင်းနှင့် ဖျော်ဖြေတင်ဆက်မှု',
        duration: 5, 
        isOptional: false, 
        onStage: true, 
        responsible: 'Tech' 
      },
      { 
        id: '15', 
        name: 'Games & Entertainment', 
        nameEn: 'Games & Entertainment',
        nameJa: '余興・ゲーム',
        nameMy: 'ဖျော်ဖြေတင်ဆက်မှုနှင့်ဂိမ်းများ',
        duration: 15, 
        isOptional: true, 
        needsMic: true, 
        onStage: true, 
        responsible: 'MC' 
      },
      { 
        id: '17', 
        name: 'Bouquet Toss & Group Photo', 
        nameEn: 'Bouquet Toss & Group Photo',
        nameJa: 'ブーケトス・集合写真',
        nameMy: 'Bouquet toss & စုပေါင်းဓာတ်ပုံရိုက်ကူးခြင်း',
        duration: 10, 
        isOptional: false, 
        responsible: 'MC' 
      },
      { 
        id: '18', 
        name: 'Seeing off Guests (Petit Gift)', 
        nameEn: 'Seeing off Guests (Petit Gift)',
        nameJa: '送賓 (プチギフト)',
        nameMy: 'ဧည့်သည်များကို ပြန်လည်ပို့ဆောင်ခြင်း (プチギフトဖြင့်)',
        duration: 30, 
        isOptional: false, 
        isImportant: true, 
        responsible: 'Couple' 
      },
      { 
        id: 'leave', 
        name: 'Couple Exit Venue', 
        nameEn: 'Couple Exit Venue',
        nameJa: '新郎新婦退館',
        nameMy: '新郎新婦退館',
        duration: 10, 
        isOptional: false, 
        responsible: 'Couple' 
      },
      { id: 'r1', name: 'Waiting for Re-entry', nameJa: '新郎新婦入場待機', nameMy: 'ပြန်လည်ဝင်ရောက်ရန် စောင့်ဆိုင်းခြင်း', duration: 10, isOptional: false, responsible: 'Couple' },
      { id: 'r2', name: 'Entrance Prep', nameJa: '入場準備', nameMy: 'ဝင်ရောက်ရန် ပြင်ဆင်ခြင်း', duration: 5, isOptional: false, responsible: 'Staff' },
      { id: 'r3', name: 'Reception Start', nameJa: '披露宴スタート', nameMy: 'ဧည့်ခံပွဲ စတင်', duration: 5, isOptional: false, isImportant: true, needsMic: true, responsible: 'MC' },
      { id: 'r4', name: 'Couple Entrance', nameJa: '新郎新婦入場', nameMy: 'သတို့သားသတို့သမီး ဝင်ရောက်ခြင်း', duration: 5, isOptional: false, isImportant: true, onStage: true, responsible: 'Couple' },
      { id: 'r5', name: 'Meal Start', nameJa: 'お料理スタート', nameMy: 'အစားအသောက် စတင်', duration: 5, isOptional: false, responsible: 'Venue' },
      { id: 'r6', name: 'Speech 1', nameJa: 'スピーチ①', nameMy: 'စကားပြော ၁', duration: 5, isOptional: false, needsMic: true, onStage: true, responsible: 'Guest' },
      { id: 'r7', name: 'Speech 2', nameJa: 'スピーチ②', nameMy: 'စကားပြော ၂', duration: 5, isOptional: false, needsMic: true, onStage: true, responsible: 'Guest' },
      { id: 'r8', name: 'Speech 3', nameJa: 'スピーチ③', nameMy: 'စကားပြော ၃', duration: 5, isOptional: false, needsMic: true, onStage: true, responsible: 'Guest' },
      { id: 'r9', name: 'Bride Exit (Change)', nameJa: '新婦中座', nameMy: 'သတို့သမီး ဝတ်စုံလဲရန် ထွက်ခွာ', duration: 15, isOptional: false, responsible: 'Bride' },
      { id: 'r10', name: 'Groom Exit (Change)', nameJa: '新郎中座', nameMy: 'သတို့သား ဝတ်စုံလဲရန် ထွက်ခွာ', duration: 15, isOptional: false, responsible: 'Groom' },
      { id: 'r11', name: 'Profile Video', nameJa: 'プロフィールＶＴＲ上映', nameMy: 'ကိုယ်ရေးအကျဉ်း ဗီဒီယို', duration: 5, isOptional: false, onStage: true, responsible: 'Tech' },
      { id: 'r12', name: 'Re-entry after Video', nameJa: '映像より続けてお二人再入場', nameMy: 'ဗီဒီယိုအပြီး ပြန်လည်ဝင်ရောက်ခြင်း', duration: 5, isOptional: false, onStage: true, responsible: 'Couple' },
      { id: 'r13', name: 'First Bite', nameJa: 'ファーストバイト', nameMy: 'ပထမဆုံး ခွံ့ကျွေးခြင်း', duration: 5, isOptional: false, onStage: true, responsible: 'Couple' },
      { id: 'r14', name: 'Table Photo Round', nameJa: 'カミングフォト', nameMy: 'စားပွဲဝိုင်း ဓာတ်ပုံရိုက်ခြင်း', duration: 20, isOptional: false, responsible: 'Couple/Photo' },
      { id: 'r15', name: 'Group Photo', nameJa: '全員写真', nameMy: 'စုပေါင်းဓာတ်ပုံ', duration: 10, isOptional: false, onStage: true, responsible: 'Photo' },
      { id: 'r16', name: 'Photo Free Time', nameJa: 'フォトフリータイム', nameMy: 'လွတ်လပ်စွာ ဓာတ်ပုံရိုက်ချိန်', duration: 15, isOptional: false, responsible: 'Guests' },
      { id: 'r17', name: 'Bride Letter', nameJa: '新婦手紙朗読', nameMy: 'သတို့သမီး စာဖတ်ခြင်း', duration: 5, isOptional: false, needsMic: true, onStage: true, responsible: 'Bride' },
      { id: 'r18', name: 'Gift Presentation', nameJa: '記念品贈呈', nameMy: 'လက်ဆောင်ပေးအပ်ခြင်း', duration: 5, isOptional: false, onStage: true, responsible: 'Couple' },
      { id: 'r19', name: 'Acknowledgment 1', nameJa: '謝辞①', nameMy: 'ကျေးဇူးတင်စကား ၁', duration: 3, isOptional: false, needsMic: true, onStage: true, responsible: 'Guest' },
      { id: 'r20', name: 'Acknowledgment 2 (Groom)', nameJa: '謝辞②新郎', nameMy: 'ကျေးဇူးတင်စကား (သတို့သား)', duration: 3, isOptional: false, needsMic: true, onStage: true, responsible: 'Groom' },
      { id: 'r21', name: 'Parents Exit', nameJa: 'ご両親退場', nameMy: 'မိဘများ ထွက်ခွာ', duration: 5, isOptional: false, responsible: 'Parents' },
      { id: 'r22', name: 'Sending Off End', nameJa: '送賓終了', nameMy: 'ဧည့်သည်ပို့ဆောင်ခြင်း ပြီးဆုံး', duration: 0, isOptional: false, isImportant: true, responsible: 'Staff' },
      { id: 'r23', name: 'Return to Bride Room', nameJa: '新郎新婦ブライズルームへ戻ります', nameMy: 'သတို့သမီးအခန်းသို့ ပြန်ခြင်း', duration: 5, isOptional: false, responsible: 'Couple' },
      { id: 'r24', name: 'After Dine', nameJa: 'アフターダイン', nameMy: 'ပွဲပြီး စားသောက်ခြင်း', duration: 30, isOptional: false, responsible: 'Couple' },
      { id: 'lib1', name: 'Meal START!', nameEn: 'Meal START!', nameJa: '食事START!', nameMy: 'အစားအသောက် စတင်!', duration: 5, isOptional: false, responsible: 'Venue' },
      { id: 'lib2', name: 'Re-entry', nameEn: 'Re-entry', nameJa: '再入場', nameMy: 'ပြန်လည်ဝင်ရောက်ခြင်း', duration: 5, isOptional: false, isImportant: true, onStage: true, responsible: 'Couple' },
      { id: 'lib3', name: 'Bride & Groom Profile Introduction', nameEn: 'Bride & Groom Profile Introduction', nameJa: '新郎新婦プロフィール紹介', nameMy: 'သတို့သားသတို့သမီး ကိုယ်ရေးအကျဉ်း မိတ်ဆက်', duration: 10, isOptional: false, needsMic: true, onStage: true, responsible: 'MC' },
      { id: 'lib4', name: 'Photo Time', nameEn: 'Photo Time', nameJa: '写真タイム', nameMy: 'ဓာတ်ပုံရိုက်ချိန်', duration: 15, isOptional: false, responsible: 'Guests' },
      {
        id: 're1',
        name: 'Cake Cutting + First Bite + First Kiss',
        nameEn: 'Cake Cutting + First Bite + First Kiss',
        nameJa: 'ケーキ入刀・ファーストバイト・ファーストキス',
        nameMy: 'ကိတ်မုန့်လှီး・ပထမ ခွံ့ကျွေး・ပထမ နမ်းရှုပ်',
        duration: 10,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Couple',
        coordinationNotes: 'Sequence: Cake cutting → First bite (groom feeds bride) → First kiss → Ring reveal to guests'
      },
      {
        id: 're2',
        name: 'Couple Exit — Flash Phone Lights',
        nameEn: 'Couple Exit — Flash Phone Lights',
        nameJa: '新郎新婦中座（フォンライト演出）',
        nameMy: 'Flash Phone Lights ပြုလုပ်ကာ ထွက်ခွာ',
        duration: 5,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Couple',
        coordinationNotes: 'Guests hold up phone flashlights as couple exits for costume change'
      },
      {
        id: 're3',
        name: 'Chuza Entertainment (Glow Sticks + Game Paper)',
        nameEn: 'Chuza Entertainment (Glow Sticks + Game Paper)',
        nameJa: '中座余興（グロースティック・ゲーム用紙配布）',
        nameMy: '中座 ဖျော်ဖြေ（Glow Sticks・ဂိမ်းစာရွက် ဝေဖြန်း）',
        duration: 15,
        isOptional: false,
        responsible: 'MC',
        coordinationNotes: 'Distribute glow sticks and game quiz paper to guests while couple changes costume'
      },
      {
        id: 're4',
        name: 'AI Profile Movie (During Chuza)',
        nameEn: 'AI Profile Movie (During Chuza)',
        nameJa: 'プロフィール映像上映（中座中・AI映像）',
        nameMy: 'Profile Movie ပြသ（中座 အတွင်း・AI映像）',
        duration: 5,
        isOptional: false,
        onStage: true,
        responsible: 'Tech',
        coordinationNotes: 'AI-generated or profile video plays while couple is offstage for costume change'
      },
      {
        id: 're5',
        name: 'Re-entrance — Laser Show & Love Speech',
        nameEn: 'Re-entrance — Laser Show & Love Speech',
        nameJa: '再入場（レーザーショー・ラブスピーチ）',
        nameMy: 'ပြန်ဝင်ရောက် Laser Show・Love Speech（Glow Stick）',
        duration: 10,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Couple',
        bgm: 'Re-entrance BGM',
        coordinationNotes: 'Laser show → couple descends from stairs → Love speech with glow sticks lit by guests'
      },
      {
        id: 're6',
        name: 'MC Quiz Game',
        nameEn: 'MC Quiz Game',
        nameJa: 'MCクイズゲーム',
        nameMy: 'MC မေးခွန်းဂိမ်း',
        duration: 15,
        isOptional: false,
        needsMic: true,
        onStage: true,
        responsible: 'MC',
        coordinationNotes: '10 questions about the couple — guests with 5+ correct answers win a gift'
      },
      {
        id: 're7',
        name: 'Flower Shower',
        nameEn: 'Flower Shower',
        nameJa: 'フラワーシャワー',
        nameMy: 'ပန်းပက်ဝေ ဆင်နှင်းခြင်း',
        duration: 5,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Guests',
        bgm: 'Flower Shower BGM'
      },
      {
        id: 're8',
        name: 'Bouquet Toss (from Stairs)',
        nameEn: 'Bouquet Toss (from Stairs)',
        nameJa: 'ブーケトス（階段より）',
        nameMy: 'Bouquet Toss（ကြေးနန်းထပ်ခေါင်မှ ပစ်ပေးခြင်း）',
        duration: 10,
        isOptional: false,
        onStage: true,
        responsible: 'Bride',
        coordinationNotes: 'Bride throws bouquet from top of stairs down to guests on the ground floor'
      },
      {
        id: 're9',
        name: 'Depart Together (1 Door)',
        nameEn: 'Depart Together (1 Door)',
        nameJa: 'お二人一緒にご退場（1ドア）',
        nameMy: 'နှစ်ဦးအတူ ထွက်ခွာ（တံခါးတစ်ပေါက်မှ）',
        duration: 5,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Couple',
        bgm: 'Departure BGM',
        coordinationNotes: 'Both exit through one door together — final moment guests see the couple'
      },
    ]
  },
  {
    name: 'Photos & Transitions',
    activities: [
      { 
        id: '10', 
        name: 'Group Photos', 
        nameEn: 'Group Photos',
        nameJa: 'グループ写真',
        nameMy: 'အဖွဲ့လိုက်ဓာတ်ပုံရိုက်ချိန်',
        duration: 10, 
        isOptional: false, 
        onStage: true, 
        responsible: 'Photographer' 
      },
      {
        id: '11',
        name: 'Costume Change',
        nameEn: 'Costume Change',
        nameJa: 'お色直し',
        nameMy: 'သတို့သား၊ သတို့သမီး ဝတ်စုံလဲလှယ်ရန် ခေတထွက်ခွာခြင်း',
        duration: 30,
        isOptional: true,
        isImportant: true,
        responsible: 'Couple'
      },
    ]
  },
  {
    name: 'Daytime Luncheon',
    activities: [
      {
        id: 'dl1',
        name: 'Dressing Room + Rehearsal',
        nameEn: 'Dressing Room + Rehearsal',
        nameJa: '控室入り・リハーサル',
        nameMy: 'ဝတ်စုံပြင်ဆင်ခြင်းနှင့် အစမ်းလေ့ကျင့်',
        duration: 60,
        isOptional: false,
        isPrep: true,
        responsible: 'Couple',
        coordinationNotes: 'Couple arrives at venue. Hair, makeup, outfit prep. Rehearsal as needed.',
        coordinationNotesJa: '控室へのご案内。ヘアメイク・お支度。リハーサル実施。',
      },
      {
        id: 'dl2',
        name: 'Wedding Ceremony on Stage',
        nameEn: 'Wedding Ceremony on Stage',
        nameJa: 'ウェディングセレモニー 🎭',
        nameMy: 'မင်္ဂလာပွဲ ကျင်းပခြင်း (ステージ)',
        duration: 15,
        isOptional: false,
        isImportant: true,
        onStage: true,
        needsMic: true,
        responsible: 'MC',
        coordinationNotes: 'Ceremony on stage: Vow exchange → Ring exchange → Flower/blessing. MC supports from stage right.',
        coordinationNotesJa: 'ステージにてセレモニー。誓いの言葉 → 指輪交換 → 花束贈呈・祝福。MCはステージ右側より進行サポート。',
        staffNotes: {
          mc: 'Cue each step: vow → ring → flower.',
          photo: 'Front of stage: close-up vow, ring on finger, flower moment.',
          lighting: 'Soft warm ceremony lighting. No sudden changes.',
          escort: 'Ensure ceremony participants (flower bearer, ring bearer) are in position before start.',
        },
        subActivities: [
          { id: 'dl2-vow', name: 'Vow Exchange', nameJa: '誓いの言葉', duration: 5, startOffset: 0, isOptional: false },
          { id: 'dl2-ring', name: 'Ring Exchange', nameJa: '指輪交換', duration: 5, startOffset: 5, isOptional: false },
          { id: 'dl2-flower', name: 'Flower / Blessing', nameJa: '花束贈呈・祝福', duration: 5, startOffset: 10, isOptional: false },
        ],
      },
      {
        id: 'dl3',
        name: 'Couple Table Greeting Rounds',
        nameEn: 'Couple Table Greeting Rounds',
        nameJa: 'お二人テーブル挨拶回り 🎭',
        nameMy: 'ဇနီးမောင်နှံ စားပွဲများသို့ ကြိုဆိုနှုတ်ဆက်',
        duration: 15,
        isOptional: false,
        responsible: 'Couple',
        coordinationNotes: 'Couple visits each table to greet guests right after ceremony (~5 min per table). Photographer follows.',
        coordinationNotesJa: 'セレモニー後、お二人が各テーブルをラウンドしてご挨拶。各テーブル約5分。カメラマン随行。',
        staffNotes: {
          photo: 'Follow couple to each table for candid greeting photos.',
          escort: 'Guide couple from table to table. Keep them on schedule.',
        },
      },
      {
        id: 'dl4',
        name: 'Cross Toast + First Kiss',
        nameEn: 'Cross Toast + First Kiss',
        nameJa: 'クロストースト・ファーストキス',
        nameMy: 'Cross Toast + ပထမနမ်းရှုပ်ခြင်း',
        duration: 5,
        isOptional: true,
        onStage: true,
        responsible: 'Couple',
        coordinationNotes: 'After Campai: couple interlock arms and drink together (cross toast) → first kiss.',
        coordinationNotesJa: '乾杯後：お二人が腕を絡めてお飲み（クロストースト）→ ファーストキス。',
        staffNotes: {
          photo: 'Capture cross toast arm interlock + first kiss — do not miss!',
        },
      },
      {
        id: 'dl5',
        name: 'Love Speech (Couple to Each Other)',
        nameEn: 'Love Speech (Couple to Each Other)',
        nameJa: 'ラブスピーチ（お互いに）',
        nameMy: 'Love Speech（နှစ်ဦးအချင်းချင်း）',
        duration: 10,
        isOptional: false,
        needsMic: true,
        onStage: true,
        responsible: 'Couple',
        coordinationNotes: 'Groom reads love speech to bride, then bride to groom. Seated at chairs by main table.',
        coordinationNotesJa: '新郎→新婦、新婦→新郎の順でラブスピーチ。メインテーブルの椅子に着席して。',
        staffNotes: {
          mc: 'Introduce love speech segment. Cue groom then bride.',
          photo: 'Capture emotional reactions of both during speech.',
        },
      },
      {
        id: 'dl6',
        name: 'Lottery Game (Gift Tag Numbers)',
        nameEn: 'Lottery Game (Gift Tag Numbers)',
        nameJa: 'ゲーム（抽選：引き出物番号）',
        nameMy: 'ဂိမ်း（ကံစမ်းမဲ：လက်ဆောင်ထုပ် နံပါတ်）',
        duration: 15,
        isOptional: true,
        needsMic: true,
        responsible: 'MC',
        coordinationNotes: 'MC draws numbers from gift bag tags. Matching guests win a prize. Prepare 5 prizes.',
        coordinationNotesJa: '★ギフト用意。引き出物に貼ってある番号でくじ引き。MCが番号を引き、当選者に景品（5個）をプレゼント。',
        staffNotes: {
          mc: 'Draw gift tag numbers. Announce winner. Gift + photo with couple.',
          escort: 'Hand prizes to MC before game starts. Escort winners to front for photo.',
        },
      },
      {
        id: 'dl7',
        name: 'Slideshow / Movie Screening (During Dress Change)',
        nameEn: 'Slideshow / Movie Screening (During Dress Change)',
        nameJa: 'スライドショー・ムービー上映（中座中）',
        nameMy: 'Slideshow/Movie ပြသ（ဝတ်စုံလဲစဉ်）',
        duration: 15,
        isOptional: false,
        responsible: 'Tech/MC',
        coordinationNotes: 'Play profile slideshow or movie while couple changes. MC hosts the screening.',
        coordinationNotesJa: 'お色直し中にスライドショーまたはムービーを上映。MC→ゲストへ案内しながら進行。',
        staffNotes: {
          mc: 'Host screening. Keep guests engaged with commentary.',
          lighting: 'Dim venue lights for screen visibility during screening.',
        },
      },
      {
        id: 'dl8',
        name: 'Re-entrance — Groom from Door / Bride from Stairs',
        nameEn: 'Re-entrance — Groom from Door / Bride from Stairs',
        nameJa: '再入場（新郎：ドア / 新婦：階段） 🎭',
        nameMy: 'ပြန်ဝင်ရောက်（သတို့သား：တံခါး / သတို့သမီး：ကြေးနန်း）',
        duration: 5,
        isOptional: false,
        isImportant: true,
        onStage: true,
        responsible: 'Couple',
        bgm: 'Re-entrance BGM',
        coordinationNotes: 'MC countdown. Groom enters from 1F door. Bride descends from stairs. Groom meets bride at staircase base → walk to stage together.',
        coordinationNotesJa: 'MC→カウントダウン。新郎が1Fドアより先に入場し、階段の下で新婦を待つ。新婦が階段を降りてくる（降壇）→ お二人でステージへ。',
        staffNotes: {
          mc: 'Countdown to cue both entrances simultaneously.',
          photo: 'Staircase base: capture bride descent + groom waiting + first look reaction.',
          lighting: 'Spotlight on staircase. Bright as bride descends.',
          escort: 'Position groom at 1F door. Confirm bride is ready at top of stairs before MC countdown.',
        },
      },
      {
        id: 'dl9',
        name: 'Bouquet Present to Friend',
        nameEn: 'Bouquet Present to Friend',
        nameJa: 'ブーケプレゼント（特定の方へ）',
        nameMy: 'Bouquet ပေးအပ်ခြင်း（သူငယ်ချင်းတစ်ဦးသို့）',
        duration: 5,
        isOptional: true,
        responsible: 'Bride',
        coordinationNotes: 'Bride presents bouquet directly to a chosen friend (no random toss). Confirm recipient with couple in advance.',
        coordinationNotesJa: '新婦が事前に決めた友人1名にブーケを直接プレゼント（ランダムトスなし）。事前にお二人より受け取る方の名前を確認。',
        staffNotes: {
          escort: 'Quietly confirm the chosen recipient name with couple before this moment.',
        },
      },
    ],
  },
  {
    name: 'Standard Morning Wedding',
    activities: [
      {
        id: 'sm-p1',
        name: 'Team Arrival & Morning Briefing',
        nameEn: 'Team Arrival & Morning Briefing',
        nameJa: 'チーム集合・朝礼',
        nameMy: 'အဖွဲ့ ရောက်ရှိ / မနက်ပိုင်း ညိနှိုင်းမှု',
        duration: 30,
        isOptional: false,
        isPrep: true,
        responsible: 'Planner',
        coordinationNotes: '9:00 All staff arrive at venue. Planner briefs MC, photo, video, escort teams: review full run-of-show, cue points, BGM list, positions.',
        coordinationNotesJa: '9:00 全スタッフ集合。プランナーより本日の進行・BGMリスト・スタッフポジション・キューポイントを共有。MC・フォト・ビデオ・エスコートで役割確認。',
        staffNotes: {
          mc: '9:00 Receive full run-of-show from planner. Confirm BGM ① ② ③ cue list and mic settings.',
          photo: '9:00 Confirm shooting schedule. Check battery, SD cards, lenses for all cameras.',
          escort: '9:00 Review entrance positions, standby spots, and couple support cues with planner.',
        },
      },
      {
        id: 'sm-p2',
        name: 'Outside Venue Prep / Reception Setup / Camera Setup',
        nameEn: 'Outside Venue Prep / Reception Setup / Camera Setup',
        nameJa: '会場外準備・受付設営・カメラ設置',
        nameMy: 'ဝင်းပြင်ပ ပြင်ဆင်မှု / ဧည့်ကြိုစားပွဲ / ကင်မရာ ထား',
        duration: 60,
        isOptional: false,
        isPrep: true,
        responsible: 'Staff',
        coordinationNotes: '9:30 Outside venue decoration and signage. Lobby reception table setup: seating chart, sign-in book, gift table. Photo/video team sets up camera positions inside venue.',
        coordinationNotesJa: '9:30 会場外デコレーション・看板設置。ロビーの受付台セッティング：席次表・芳名帳・ギフトテーブル。フォト・ビデオチームは会場内カメラポジション設置開始。',
        staffNotes: {
          photo: '9:30 Setup all cameras. Scout key angles: entrance door, stage, staircase, cake table. Test indoor lighting conditions.',
          escort: '9:30 Set up reception table. Prepare seating charts, gift table, welcome board.',
        },
      },
      {
        id: 'sm-p3',
        name: 'Inside Venue Prep + Dressing Room (Rehearsal / Sound / AV Check)',
        nameEn: 'Inside Venue Prep + Dressing Room (Rehearsal / Sound / AV Check)',
        nameJa: '会場内準備・お支度（リハーサル・音響・映像確認）',
        nameMy: 'ဝင်းတွင်း ပြင်ဆင်မှု / ဝတ်စုံ（Rehearsal / Sound / AV）',
        duration: 60,
        isOptional: false,
        isPrep: true,
        responsible: 'MC/Staff',
        coordinationNotes: '10:30 Venue opens for inside prep. Couple enters dressing room. MC, planner, and ceremony participants begin: full event rehearsal, sound system check (BGM levels, mic), video/projection system check, slideshow test. Venue decor final adjustment.',
        coordinationNotesJa: '10:30 会場内準備スタート。お二人は控室へ。MC・プランナー・参加者とともにリハーサル開始。音響確認（BGMレベル・マイク）、映像・プロジェクター確認、スライドショーテスト。会場装飾最終調整。',
        staffNotes: {
          mc: '10:30 Full rehearsal with planner: cue timing, BGM test ①②③, mic level check, opening/closing speech run-through.',
          photo: '10:30 Final camera positioning. Test ceremony lighting. Confirm video system and projection screen.',
          escort: '10:30 Assist couple setup in dressing room. Confirm ceremony participants (ring bearer, flower bearer) are present and briefed.',
          lighting: '10:30 Test all lighting scenes: entrance spotlight, stage ceremony light, staircase spotlight, cake table spot.',
        },
      },
      {
        id: 'sm-p4',
        name: 'Reception Start + Rehearsal Photoshoot',
        nameEn: 'Reception Start + Rehearsal Photoshoot',
        nameJa: '受付スタート・リハーサル撮影',
        nameMy: 'ဧည့်ကြိုစတင် / Rehearsal ဓာတ်ပုံ',
        duration: 20,
        isOptional: false,
        isPrep: true,
        responsible: 'Receptionist/Photographer',
        coordinationNotes: '11:30 Guest reception opens in lobby (seating chart distribution). Simultaneously: rehearsal photoshoot with couple inside venue — test key positions for ceremony, stage, and entrance shots.',
        coordinationNotesJa: '11:30 ロビーにて受付スタート（席次表のご案内）。同時に会場内でリハーサル撮影：セレモニーの立ち位置・ステージ・入場ポジションのテスト撮影。',
        staffNotes: {
          photo: '11:30 Rehearsal photoshoot with couple: practice entrance walk, stage positions, ring exchange stance. Verify lighting and angles.',
          escort: '11:30 Staff one at reception desk. Remaining escort: bring couple from dressing room for rehearsal shoot, then return to dressing room.',
        },
      },
      {
        id: 'sm-p5',
        name: 'Guests Seated + MC Welcome + Standby',
        nameEn: 'Guests Seated + MC Welcome + Standby',
        nameJa: 'ゲスト着席・MCウェルカム・スタンバイ',
        nameMy: 'ဧည့်သည် 着席 / MC ကြိုဆိုစကား / Standby',
        duration: 10,
        isOptional: false,
        isPrep: true,
        responsible: 'MC/Escort',
        coordinationNotes: '11:50 Escort guests from lobby into venue and to their seats. MC delivers short welcome address from stage. Couple moves to backstage standby position. All teams in final position.',
        coordinationNotesJa: '11:50 エスコートがゲストをロビーから会場内へご案内・着席。MCよりウェルカムスピーチ（短め）。お二人はバックステージへ移動・スタンバイ。全スタッフ最終ポジションへ。',
        staffNotes: {
          mc: '11:50 Short welcome address to guests while they are being seated. Confirm couple is in position. Cue BGM ① standby.',
          photo: '11:50 Final position: inside venue, capture guests being seated. Ready for entrance.',
          escort: '11:50 Guide guests from lobby to seats. Bring couple to backstage standby position.',
        },
      },
      {
        id: 'sm-e1',
        name: 'Guest Send-off',
        nameEn: 'Guest Send-off',
        nameJa: 'ゲストお見送り',
        nameMy: 'ဧည့်သည် ပို့ဆောင်ခြင်း',
        duration: 30,
        isOptional: false,
        responsible: 'Couple',
        coordinationNotes: 'Couple stands at lobby or venue exit. Farewell each guest personally. Petit gift + wedding gift handed to each.',
        coordinationNotesJa: 'お二人がロビー入口に立ちゲスト一人ひとりをお見送り。プチギフト＋引出物を手渡し。',
        staffNotes: {
          photo: 'Capture farewell moments and candid emotional goodbyes at lobby exit.',
          escort: 'Assist with gift handout. Keep couple in position at exit.',
        },
      },
      {
        id: 'sm-e2',
        name: 'Change / Settlement / Checkout',
        nameEn: 'Change / Settlement / Checkout',
        nameJa: '着替え・精算・退出',
        nameMy: 'ဝတ်စုံပြန်လဲ / ငွေစာရင်းဆော / ထွက်ခွာ',
        duration: 30,
        isOptional: false,
        responsible: 'Couple/Planner',
        coordinationNotes: 'Couple returns to dressing room to change. Planner handles final billing settlement with venue. All belongings collected. Complete checkout by scheduled time.',
        coordinationNotesJa: 'お二人は控室へ戻りお着替え。プランナーは会場との精算対応。お荷物のまとめ・退出。予定時刻までに退出完了。',
      },
    ],
  },
];
